version: "3.9"

services:
  # A customized instance of collectivo for Hermes.
  collectivo:
    restart: always

    build: ./collectivo
    volumes:
      - ./collectivo/collectivo.yml:/collectivo_app/collectivo.yml
      - ./collectivo/extensions/hermes:/collectivo_app/hermes
      - ./disposerv:/collectivo_app/hermes/disposerv
      - ./uploads:/collectivo_app/media_root
      - ../collectivo/collectivo_app:/collectivo_app
      - ../collectivo/collectivo:/collectivo_app/collectivo
    command: >
      sh -c "while ! nc -z collectivo-db 5432; do sleep 1; done &&
             while ! nc -z keycloak 8080; do sleep 1; done &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000
             "
    environment:
      DB_HOST: collectivo-db
      DB_NAME: collectivo_db
      DB_USER: ${COLLECTIVO_DB_USER}
      DB_PASS: ${COLLECTIVO_DB_PASSWORD}
      SECRET_KEY: ${COLLECTIVO_SECRET_KEY}
      ALLOWED_HOSTS: ${COLLECTIVO_URL}
      ALLOWED_ORIGINS: ${COLLECTIVO_UX_URL}
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_CLIENT_SECRET: ${COLLECTIVO_KEYCLOAK_CLIENT_SECRET}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USE_SSL: ${EMAIL_USE_SSL}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      CELERY_BROKER: ${REDIS_URL}
      CELERY_BACKEND: ${REDIS_URL}
      VIRTUAL_HOST: ${COLLECTIVO_URL_BASE}
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST: ${COLLECTIVO_URL_BASE}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      ADMIN_USER: ${COLLECTIVO_ADMIN_USER}
      ADMIN_PASS: ${COLLECTIVO_ADMIN_PASS}
      DISPOSERV_SERVER_URL: ${DISPOSERV_SERVER_URL}
      COLLECTIVO_KEYCLOAK_SERVER_URL: http://keycloak:8080
    labels:
      io.portainer.accesscontrol.teams: ${PORTAINER_TEAM_ID}
    depends_on:
      - collectivo-db
      - keycloak
      - redis
    ports:
      - "8000:8000"
    links:
      - keycloak

  # A celery worker that runs in the background.
  # Image & environment should be the same as collectivo-mila.
  celery:
    restart: always
    build: ./collectivo
    command: celery -A collectivo_app worker -l info
    volumes:
      - ./collectivo/collectivo.yml:/collectivo_app/collectivo.yml
      - ./collectivo/extensions/hermes:/collectivo_app/hermes
      - ./disposerv:/collectivo_app/hermes/disposerv
      - ./uploads:/collectivo_app/media_root
      - ../collectivo/collectivo_app:/collectivo_app
      - ../collectivo/collectivo:/collectivo_app/collectivo
    environment:
      DB_HOST: collectivo-db
      DB_NAME: collectivo_db
      DB_USER: ${COLLECTIVO_DB_USER}
      DB_PASS: ${COLLECTIVO_DB_PASSWORD}
      SECRET_KEY: ${COLLECTIVO_SECRET_KEY}
      ALLOWED_HOSTS: ${COLLECTIVO_URL}
      ALLOWED_ORIGINS: ${COLLECTIVO_UX_URL}
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_CLIENT_SECRET: ${COLLECTIVO_KEYCLOAK_CLIENT_SECRET}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USE_SSL: ${EMAIL_USE_SSL}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      CELERY_BROKER: ${REDIS_URL}
      CELERY_BACKEND: ${REDIS_URL}
      VIRTUAL_HOST: ${COLLECTIVO_URL_BASE}
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST: ${COLLECTIVO_URL_BASE}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    labels:
      io.portainer.accesscontrol.teams: ${PORTAINER_TEAM_ID}
    depends_on:
      - collectivo
      - redis
    links:
      - collectivo-db

  # A celery worker that runs in the background and processes the scheduled tasks.
  celery-beat:
    restart: always
    build: ./collectivo
    command: celery -A collectivo_app beat -l info
    volumes:
      - ./collectivo/collectivo.yml:/collectivo_app/collectivo.yml
      - ./collectivo/extensions/hermes:/collectivo_app/hermes
      - ./disposerv:/collectivo_app/hermes/disposerv
      - ./uploads:/collectivo_app/media_root
      - ../collectivo/collectivo_app:/collectivo_app
      - ../collectivo/collectivo:/collectivo_app/collectivo
    environment:
      DB_HOST: collectivo-db
      DB_NAME: collectivo_db
      DB_USER: ${COLLECTIVO_DB_USER}
      DB_PASS: ${COLLECTIVO_DB_PASSWORD}
      SECRET_KEY: ${COLLECTIVO_SECRET_KEY}
      ALLOWED_HOSTS: ${COLLECTIVO_URL}
      ALLOWED_ORIGINS: ${COLLECTIVO_UX_URL}
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_CLIENT_SECRET: ${COLLECTIVO_KEYCLOAK_CLIENT_SECRET}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USE_SSL: ${EMAIL_USE_SSL}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      CELERY_BROKER: ${REDIS_URL}
      CELERY_BACKEND: ${REDIS_URL}
      VIRTUAL_HOST: ${COLLECTIVO_URL_BASE}
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST: ${COLLECTIVO_URL_BASE}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    labels:
      io.portainer.accesscontrol.teams: ${PORTAINER_TEAM_ID}
    depends_on:
      - collectivo
      - redis
    links:
      - collectivo-db

  # A communication broker for celery.
  redis:
    image: redis:7.0-alpine
    command: >
      --requirepass "${REDIS_PASSWORD}" --appendonly yes --maxmemory 1000mb
      --maxmemory-policy volatile-lru
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    deploy:
      resources:
        limits:
          memory: 1024M
    labels:
      io.portainer.accesscontrol.teams: ${PORTAINER_TEAM_ID}

  # A PostgreSQL database.
  collectivo-db:
    image: postgres:14-alpine
    volumes:
      - collectivo-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: collectivo_db
      POSTGRES_USER: ${COLLECTIVO_DB_USER}
      POSTGRES_PASSWORD: ${COLLECTIVO_DB_PASSWORD}
    ports:
      - "5432:5432"
    labels:
      io.portainer.accesscontrol.teams: ${PORTAINER_TEAM_ID}

  # A frontend web application.
  collectivo-ux:
    image: milawien/collectivo-ux:latest
    restart: always
    environment:
      VIRTUAL_HOST: ${COLLECTIVO_UX_URL_BASE}
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ${COLLECTIVO_UX_URL_BASE}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VITE_API_URL: ${COLLECTIVO_URL}
      VITE_KEYCLOAK_URL: http://keycloak:8080
    labels:
      io.portainer.accesscontrol.teams: ${PORTAINER_TEAM_ID}
    ports:
      - "8001:80"

  # Database for keycloak
  keycloak-db:
    image: postgres:14-alpine
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    labels:
      io.portainer.accesscontrol.teams: ${PORTAINER_TEAM_ID}

  # Keycloak for authentication.
  keycloak:
    build: ./docker/keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      ROOT_LOGLEVEL: ALL
      KEYCLOAK_LOGLEVEL: DEBUG
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1:8080/realms/master"]
      interval: 5s
      timeout: 2s
      retries: 15
    volumes:
      - ./docker/keycloak/import:/opt/keycloak/data/import:ro
      - ./docker/keycloak/themes/hermes:/opt/keycloak/themes/hermes:ro
      - ./docker/keycloak/export:/tmp/export
      - ./docker/keycloak/healthcheck.sh:/healthcheck.sh
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    labels:
      io.portainer.accesscontrol.teams: ${PORTAINER_TEAM_ID}

volumes:
  collectivo-db-data:
  keycloak-db-data:
