# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-27 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, default='', max_length=300)),
                ('number', models.CharField(blank=True, max_length=10)),
                ('stair', models.CharField(blank=True, max_length=10)),
                ('level', models.CharField(blank=True, max_length=10)),
                ('door', models.CharField(blank=True, max_length=10)),
                ('extra', models.CharField(blank=True, max_length=300)),
                ('postal_code', models.CharField(blank=True, max_length=6)),
                ('talk_to', models.CharField(blank=True, default='', max_length=400)),
                ('talk_to_extra', models.CharField(blank=True, default='', max_length=400)),
                ('lat', models.FloatField(default=48.216618, null=True)),
                ('lon', models.FloatField(default=16.385031, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('zone', models.PositiveIntegerField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('extra', models.FloatField(null=True)),
                ('type', models.CharField(default='einzelfahrt', max_length=100)),
                ('fromrepeated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContractPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('start_mode', models.CharField(default='ab', max_length=10)),
                ('start_time', models.DateTimeField()),
                ('anon_name', models.CharField(blank=True, default='', max_length=300)),
                ('weight_size_bonus', models.CharField(blank=True, default='', max_length=10)),
                ('is_cargo', models.BooleanField(default=False)),
                ('is_express', models.BooleanField(default=False)),
                ('is_bigbuilding', models.BooleanField(default=False)),
                ('get_there_bonus', models.FloatField(default=0.0)),
                ('waiting_bonus', models.IntegerField(default=0)),
                ('memo', models.TextField(blank=True)),
                ('distance', models.FloatField(default=0.0, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('bonus', models.FloatField(default=0.0)),
                ('zone', models.IntegerField(default=1, null=True)),
                ('phone_1', models.CharField(blank=True, default='', max_length=300)),
                ('email', models.CharField(blank=True, default='', max_length=300)),
                ('talk_to', models.CharField(blank=True, default='', max_length=400)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='disposerv.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('external_id', models.IntegerField(default='-1')),
                ('phone_1', models.CharField(blank=True, max_length=100)),
                ('phone_2', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=300)),
                ('name', models.CharField(max_length=200)),
                ('payment', models.CharField(default='Bar', max_length=10)),
                ('has_delayed_payment', models.BooleanField(default=False)),
                ('has_delayed_payment_memo', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('added',),
            },
        ),
        migrations.CreateModel(
            name='Dispo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('preliminary', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disposerv.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='Repeated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(null=True)),
                ('movable_date', models.DateTimeField(default=None, null=True)),
                ('days_of_the_week', models.CharField(blank=True, max_length=60)),
                ('contract', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repeated', to='disposerv.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=400)),
                ('name_street', models.CharField(default='', max_length=400)),
                ('nr_von', models.CharField(max_length=10, null=True)),
                ('nr_bis', models.CharField(max_length=10, null=True)),
                ('postal_code', models.CharField(max_length=4)),
                ('lat', models.FloatField(default=16)),
                ('lon', models.FloatField(default=48)),
            ],
        ),
        migrations.CreateModel(
            name='TimesRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('mode', models.CharField(default='fahrer', max_length=10)),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='times', to='disposerv.Staff')),
            ],
        ),
        migrations.AddField(
            model_name='dispo',
            name='dispatched_to',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='disposerv.Staff'),
        ),
        migrations.AddField(
            model_name='dispo',
            name='position',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='dispo', to='disposerv.ContractPosition'),
        ),
        migrations.AddField(
            model_name='contractposition',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='disposerv.Customer'),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disposerv.Customer'),
        ),
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='disposerv.Customer'),
        ),
        migrations.AddField(
            model_name='address',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='disposerv.ContractPosition'),
        ),
    ]
