# Generated by Django 4.0.4 on 2022-05-12 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disposerv', '0003_auto_20190928_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='disposerv.customer'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='disposerv.customer'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='fromrepeated',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='contractposition',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='disposerv.customer'),
        ),
    ]
