# Generated by Django 4.0.4 on 2022-05-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposerv', '0005_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='addzone_size',
            field=models.FloatField(default=2.0),
        ),
    ]
