# Generated by Django 4.0.4 on 2022-08-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposerv', '0006_settings_addzone_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='repeated_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
