# Generated by Django 4.1.7 on 2023-05-02 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disposerv', '0010_alter_historicalstaff_id_alter_staff_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalstaff',
            old_name='id',
            new_name='old_id',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='id',
            new_name='old_id',
        ),
    ]
