# Generated by Django 4.1.7 on 2023-05-02 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disposerv', '0012_remove_historicalstaff_old_id_remove_staff_old_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstaff',
            name='name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='name',
        ),
    ]
