# Generated by Django 4.1.9 on 2023-06-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposerv', '0013_remove_historicalstaff_name_remove_staff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='city',
            field=models.CharField(default='Wien', max_length=100),
        ),
    ]
