# Generated by Django 4.1.10 on 2023-08-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposerv', '0014_settings_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractposition',
            name='pickup_time_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractposition',
            name='pickup_time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractposition',
            name='pickup_time_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractposition',
            name='storage',
            field=models.BooleanField(default=False),
        ),
    ]
