# Generated by Django 4.1.10 on 2023-08-09 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disposerv', '0016_settings_gps_lat_settings_gps_lon'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(default=48.216618, null=True)),
                ('lon', models.FloatField(default=16.385031, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StreetWithNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=400)),
                ('nr', models.CharField(max_length=10, null=True)),
                ('postal_code', models.CharField(max_length=4)),
                ('lat', models.FloatField(default=16)),
                ('lon', models.FloatField(default=48)),
            ],
        ),
        migrations.AddIndex(
            model_name='streetwithnumber',
            index=models.Index(fields=['name', 'nr'], name='disposerv_s_name_9def91_idx'),
        ),
        migrations.AddField(
            model_name='addressposition',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='disposerv.address'),
        ),
        migrations.AddField(
            model_name='addressposition',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addressposition', to='disposerv.contractposition'),
        ),
    ]
