# Generated by Django 4.1.7 on 2023-03-24 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SurveySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='registration_survey', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('survey_contact', models.TextField(blank=True, null=True)),
                ('survey_motivation', models.TextField(blank=True, null=True)),
                ('groups_interested', models.ManyToManyField(blank=True, related_name='groups_interested', to='registration.surveygroup')),
                ('skills', models.ManyToManyField(blank=True, to='registration.surveyskill')),
            ],
        ),
    ]
