# Generated by Django 4.1.10 on 2023-08-24 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disposerv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repeated',
            name='movable_date',
        ),
        migrations.CreateModel(
            name='RepeatedContractForDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('created', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('changed', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repeatedcontracts', to='disposerv.contract')),
                ('repeated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repeatedcontracts', to='disposerv.repeated')),
            ],
        ),
    ]
