# Generated by Django 4.1.10 on 2023-08-24 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disposerv', '0002_remove_repeated_movable_date_repeatedcontractfordate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repeatedcontractfordate',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repeatedcontracts', to='disposerv.contract'),
        ),
        migrations.AlterField(
            model_name='repeatedcontractfordate',
            name='repeated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repeatedcontracts', to='disposerv.repeated'),
        ),
    ]
