# Generated by Django 4.0.4 on 2022-05-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposerv', '0004_alter_address_customer_alter_contract_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basezone_price', models.FloatField(default=8.0)),
                ('addzone_price', models.FloatField(default=4.0)),
                ('express_price', models.FloatField(default=4.0)),
                ('express_price_zone_size', models.IntegerField(default=2)),
                ('zone_size', models.FloatField(default=3.0)),
            ],
        ),
    ]
