# Generated by Django 4.1.7 on 2023-05-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposerv', '0009_staff_isdispo_staff_user_historicalstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstaff',
            name='id',
            field=models.IntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
