# Generated by Django 4.1.7 on 2023-05-02 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disposerv', '0011_rename_id_historicalstaff_old_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstaff',
            name='old_id',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='old_id',
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='disposerv_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
