# Generated by Django 4.1.10 on 2023-08-21 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disposerv', '0017_addressposition_streetwithnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeatedContractPosition',
            fields=[
                ('contractposition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='disposerv.contractposition')),
            ],
            bases=('disposerv.contractposition',),
        ),
        migrations.RemoveField(
            model_name='contractposition',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='contractposition',
            name='pickup_time_at',
        ),
        migrations.RemoveField(
            model_name='contractposition',
            name='pickup_time_end',
        ),
        migrations.RemoveField(
            model_name='contractposition',
            name='pickup_time_start',
        ),
        migrations.RemoveField(
            model_name='contractposition',
            name='start_mode',
        ),
        migrations.AddField(
            model_name='contract',
            name='repeated_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='contractposition',
            name='contractor_is_pick_up',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contractposition',
            name='drop_off_place',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer2', to='disposerv.customer'),
        ),
        migrations.AddField(
            model_name='contractposition',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractposition',
            name='end_time_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractposition',
            name='pick_up_place',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='disposerv.customer'),
        ),
        migrations.AddField(
            model_name='contractposition',
            name='start_time_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repeated',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contractposition',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RepeatedContract',
            fields=[
                ('contract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='disposerv.contract')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='disposerv.repeatedcontractposition')),
            ],
            bases=('disposerv.contract',),
        ),
        migrations.AlterField(
            model_name='repeated',
            name='contract',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repeated', to='disposerv.repeatedcontract'),
        ),
    ]
