# Generated by Django 4.1.10 on 2023-08-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposerv', '0019_alter_contract_repeated_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractposition',
            old_name='pick_up_place',
            new_name='costumer',
        ),
        migrations.RemoveField(
            model_name='contractposition',
            name='contractor_is_pick_up',
        ),
        migrations.RemoveField(
            model_name='contractposition',
            name='drop_off_place',
        ),
        migrations.AddField(
            model_name='contractposition',
            name='costumer_is_drop_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractposition',
            name='costumer_is_pick_up',
            field=models.BooleanField(default=True),
        ),
    ]
