# Generated by Django 4.1.10 on 2023-08-22 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disposerv', '0020_rename_pick_up_place_contractposition_costumer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractposition',
            old_name='costumer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='contractposition',
            old_name='costumer_is_drop_off',
            new_name='customer_is_drop_off',
        ),
        migrations.RenameField(
            model_name='contractposition',
            old_name='costumer_is_pick_up',
            new_name='customer_is_pick_up',
        ),
    ]
