# Generated by Django 4.1.8 on 2023-05-04 05:59

import collectivo.utils.models
from django.db import migrations, models
import mila.lotzapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LotzappAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotzapp_id', models.CharField(blank=True, max_length=255)),
            ],
            bases=(mila.lotzapp.models.LotzappMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LotzappInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotzapp_id', models.CharField(blank=True, max_length=255, unique=True)),
            ],
            bases=(mila.lotzapp.models.LotzappMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LotzappSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotzapp_url', models.URLField(max_length=255)),
                ('lotzapp_user', models.CharField(max_length=255)),
                ('lotzapp_pass', models.CharField(max_length=255)),
                ('zahlungsmethode_sepa', models.IntegerField(null=True)),
                ('zahlungsmethode_transfer', models.IntegerField(null=True)),
                ('adressgruppe_eg', models.IntegerField(null=True)),
                ('adressgruppe_verein', models.IntegerField(null=True)),
            ],
            bases=(collectivo.utils.models.SingleInstance, models.Model),
        ),
    ]
