# Generated by Django 4.1.8 on 2023-05-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotzapp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotzappSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failure', 'failure')], default='pending', max_length=255)),
                ('type', models.CharField(choices=[('invoice', 'invoice'), ('address', 'address')], max_length=255)),
                ('status_message', models.TextField()),
            ],
        ),
    ]
