# Generated by Django 4.1.8 on 2023-05-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotzapp', '0003_lotzappsync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotzappinvoice',
            name='lotzapp_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
