# Generated by Django 4.1.8 on 2023-05-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotzapp', '0004_alter_lotzappinvoice_lotzapp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotzappsync',
            name='type',
            field=models.CharField(choices=[('invoice', 'Rechnungen & zugehörige Adressen'), ('address', 'Adressen')], max_length=255),
        ),
    ]
